version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud-get"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ay6b09izqmn9"
s3_prefix = "crud-get"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
